export const SEARCH_LIMITS = {
  DAILY_SEARCH_LIMIT: 100,
  EXTREME_SEARCH_LIMIT: 5,
} as const;

export const PRICING = {
  PRO_MONTHLY: 15,
  PRO_MONTHLY_INR: 1299,
  TEAM_PER_SEAT_MONTHLY: 12,
  TEAM_PER_SEAT_MONTHLY_INR: 999,
  ENTERPRISE_PER_SEAT_MONTHLY: 10,
  ENTERPRISE_PER_SEAT_MONTHLY_INR: 799,
  MIN_TEAM_SEATS: 3,
  MIN_ENTERPRISE_SEATS: 10,
} as const;

export const CURRENCIES = {
  USD: 'USD',
  INR: 'INR',
} as const;

export const SNAPSHOT_NAME = 'atlas-analysis:1752127473';
