// https://env.t3.gg/docs/nextjs#create-your-schema
import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

export const serverEnv = createEnv({
  server: {
    APP_URL: z.string().url().optional(),
    XAI_API_KEY: z.string().min(1),
    OPENAI_API_KEY: z.string().min(1),
    ANTHROPIC_API_KEY: z.string().min(1),
    GROQ_API_KEY: z.string().min(1),
    GOOGLE_GENERATIVE_AI_API_KEY: z.string().min(1),
    DAYTONA_API_KEY: z.string().min(1),
    DATABASE_URL: z.string().min(1),
    BETTER_AUTH_SECRET: z.string().min(1),
    GITHUB_CLIENT_ID: z.string().min(1),
    GITHUB_CLIENT_SECRET: z.string().min(1),
    GOOGLE_CLIENT_ID: z.string().min(1),
    GOOGLE_CLIENT_SECRET: z.string().min(1),
    TWITTER_CLIENT_ID: z.string().min(1),
    TWITTER_CLIENT_SECRET: z.string().min(1),
    REDIS_URL: z.string().min(1),
    ELEVENLABS_API_KEY: z.string().min(1),
    TAVILY_API_KEY: z.string().min(1),
    EXA_API_KEY: z.string().min(1),
    TMDB_API_KEY: z.string().min(1),
    YT_ENDPOINT: z.string().min(1),
    FIRECRAWL_API_KEY: z.string().min(1),
    OPENWEATHER_API_KEY: z.string().min(1),
    GOOGLE_MAPS_API_KEY: z.string().min(1),
    MAPBOX_ACCESS_TOKEN: z.string().min(1),
    AMADEUS_API_KEY: z.string().min(1),
    AMADEUS_API_SECRET: z.string().min(1),
    CRON_SECRET: z.string().min(1),
    BLOB_READ_WRITE_TOKEN: z.string().min(1),
    MEM0_API_KEY: z.string().min(1),
    MEM0_ORG_ID: z.string().min(1),
    MEM0_PROJECT_ID: z.string().min(1),
    SMITHERY_API_KEY: z.string().min(1),
    COINGECKO_API_KEY: z.string().min(1),
    QSTASH_TOKEN: z.string().min(1),
    RESEND_API_KEY: z.string().min(1),
    ALLOWED_ORIGINS: z.string().optional().default('http://localhost:3000'),
    SCIRA_TASKS_ENDPOINT: z.string().url().optional(),
    ELEVENLABS_TTS_BASE_URL: z.string().url().optional(),
    ELEVENLABS_DEFAULT_VOICE_ID: z.string().optional(),

    DAILY_SEARCH_LIMIT: z.coerce.number().optional().default(100),
    EXTREME_SEARCH_LIMIT: z.coerce.number().optional().default(5),
    DEFAULT_REVALIDATE_SECONDS: z.coerce.number().optional().default(3600),

    MAX_TASKS_PER_USER: z.coerce.number().optional().default(10),
    MAX_ACTIVE_DAILY_TASKS: z.coerce.number().optional().default(5),
    MIN_TASK_DELAY_MINUTES: z.coerce.number().optional().default(5),

    PRO_MONTHLY_USD: z.coerce.number().optional().default(15),
    PRO_MONTHLY_INR: z.coerce.number().optional().default(1299),
    TEAM_PER_SEAT_USD: z.coerce.number().optional().default(12),
    TEAM_PER_SEAT_INR: z.coerce.number().optional().default(999),
    ENTERPRISE_PER_SEAT_USD: z.coerce.number().optional().default(10),
    ENTERPRISE_PER_SEAT_INR: z.coerce.number().optional().default(799),
    MIN_TEAM_SEATS: z.coerce.number().optional().default(3),
    MIN_ENTERPRISE_SEATS: z.coerce.number().optional().default(10),

    SNAPSHOT_NAME: z.string().optional(),
  },
  experimental__runtimeEnv: process.env,
});
